title: "GA4GH Clinical & Phenotypic Data Capture & Exchange"
label: GA4GH::CP
github_organisation: ga4gh-cp
future: true
navigation_categories:
  representation: "Representation"
  exchange: "Exchange & Interoperability"
  implementation: "Implementation & Engagement"
  news: News
  howto: Examples & Guides
collections:
  representation:
    output: true
    permalink: /:collection/:name
  exchange:
    output: true
    permalink: /:collection/:name
  implementation:
    output: true
    permalink: /:collection/:name
navigation_static_links:
  ga4gh:
    url: "http://ga4gh.org"
    label: "GA4GH Main Site"
  phenopackets:
    url: "https://github.com/phenopackets"
    label: "Phenopackets PXF"
  schemablocks:
    url: "http://schemablocks.org"
    label: "SchemaBlocks"
  ga4gh-duri:
    url: "http://ga4gh-duri.github.io"
    label: "GA4GH::DURI"
  ga4gh-lsg:
    url: "https://github.com/ga4gh/large-scale-genomics-wiki/wiki/"
    label: "GA4GH Large Scale Genomics"
  ga4gh-gks:
    url: "http://ga4gh-gks.github.io"
    label: "GA4GH::GKS"
  beacon:
    url: "http://schemablocks.org"
    label: "SchemaBlocks"
navigation_max_items: 4
tag_title_prefix: ''
tag_title_suffix: ''
